# Generated by Django 4.2 on 2024-11-08 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Zay Shop", max_length=150)),
                (
                    "email",
                    models.EmailField(default="mubaarock021@gmail.com", max_length=254),
                ),
                (
                    "address",
                    models.CharField(
                        default="123 Consectetur at ligula 10660", max_length=300
                    ),
                ),
                ("phone", models.CharField(default="+2347014887266", max_length=150)),
                (
                    "fb",
                    models.URLField(
                        default="https://facebook.com",
                        max_length=300,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://twitter.com",
                        max_length=300,
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "ig",
                    models.URLField(
                        default="https://instagram.com",
                        max_length=300,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "li",
                    models.URLField(
                        default="https://linkedin.com",
                        max_length=300,
                        verbose_name="LinkedIn",
                    ),
                ),
                ("banner_img1", models.ImageField(default="", upload_to="assets/")),
                ("banner_img2", models.ImageField(default="", upload_to="assets/")),
                ("banner_img3", models.ImageField(default="", upload_to="assets/")),
                (
                    "cats_of_month",
                    models.ManyToManyField(
                        related_name="cats_of_month",
                        to="products.category",
                        verbose_name="Categories of The Month",
                    ),
                ),
                (
                    "featured_products",
                    models.ManyToManyField(
                        related_name="featured_products", to="products.product"
                    ),
                ),
            ],
        ),
    ]
