# Generated by Django 4.0.10 on 2024-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='guest_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_wishlist_item'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('guest_id', 'product'), name='unique_guest_wishlist_item'),
        ),
    ]
