# Generated by Django 4.0.10 on 2024-10-30 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_wishlist_guest_id_wishlist_unique_user_wishlist_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='guest_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('user', 'guest_id', 'product', 'order', 'size', 'color'), name='unique_user_guest_product_order_orderitems'),
        ),
    ]
